### ISSUE TITLE
[Feature] Configurable `--max-backups` parameter for etcdbrctl garbage collection

### ISSUE THREAD

**Issue by shreyas-s-rao** [gardener/etcd-druid#751] opened 2024-01-10 05:19 UTC
**Feature (What you would like to be added):**
Configurable `--max-backups` parameter for etcdbrctl garbage collection for `LimitBased` garbage collection policy.

**Motivation (Why is this needed?):**
Currently, when setting `Spec.Backup.GarbageCollectionPolicy` to `LimitBased` in the `Etcd` resource, there is no way to configure the maximum backups (limit) to retain, since it simply set to `7` by default ([code](https://github.com/gardener/etcd-druid/blob/60d9955bf63a5dad4967633b80bfe44b1e318947/pkg/component/etcd/statefulset/values_helper.go#L236)). 

**Approach/Hint to the implement solution (optional):**
Add new field `RetainMaxBackups` or `GCRetainMaxBackups` to `Etcd.Spec.Backup` section (simply using `MaxBackups` would be unclear and confusing to the end-user).

**Comment by anveshreddy18** [comment] 2024-01-11 10:27
Closing this issue as it is a duplicate of the issue #754

**Closed by anveshreddy18** 2024-01-11 10:27 UTC
Labels: kind/enhancement, size/s
